### ISSUE TITLE
[🐛 Bug] Dashboard overflow is not taken into consideration

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1283]
**Describe the bug**
If you mistakenly move dashboard widget too much down, it disappears from screen

**To Reproduce**
1. See the attached video

**Expected behavior**
User should not be able to move widgets outside of the scope of the screen or the screen should grow accordingly.

**Screenshots**

https://github.com/keephq/keep/assets/68807791/2d0d9dc1-af45-40ac-ac43-1cbca07d0b0d

**Comment by ArtArtem** [comment]
@talboren Hi, I want to try, I think I have an idea why this bug is happening

**Comment by ArtArtem** [comment]
https://github.com/keephq/keep/assets/45171843/c9e75ccc-b8dc-4aa1-8844-1a91fd13619a

@talboren @Matvey-Kuk 

The problem is solved, I think it's better for UX to choose a scrollbar solution, because clients may need to place a large number of widgets of different shapes, so a height equal to the height of the screen may not be enough, I want to hear your thoughts

**Comment by talboren** [comment]
@ArtArtem sorry for not replying earlier! Somehow I missed it. Looks awesome! Do you have a PR for it?

cc @shahargl

**Comment by ArtArtem** [comment]
@talboren, sure https://github.com/keephq/keep/pull/1365

**Comment by talboren** [comment]
@ArtArtem thank you for the contribution!
