### ISSUE TITLE
Add WSGI to the deployment

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#406]

**Comment by mohanish2504** [comment]
Hey @shahargl can you describe more?

**Comment by shahargl** [comment]
Hey @mohanish2504 ofc

The current dockerfile starts Keep with ‘keep api’ command, I though we can improve it by adding wsgi as uvicorn and make it multiprocess

**Comment by mohanish2504** [comment]
Hey can you brief me on how are we planning to run multiple process `uvicorn.run` even though gives option for `workers` doesn't work programatically.

https://www.uvicorn.org/deployment/#running-programmatically

Also, since fast api app by default ASGI we have to convert it to WSGI first.
I was able to do this will this package

https://github.com/abersheeran/a2wsgi#asgimiddleware


`def run(app: FastAPI):
    # We want to start all internal services (workflowmanager, eventsubscriber, etc) only after the server is up

    # so we init a thread that will wait for the server to be up and then start the internal services

    logger.info("Starting the run services thread")

    thread = threading.Thread(target=run_services_after_app_is_up)

    thread.start()

    logger.info("Starting the uvicorn server")

    app = ASGIMiddleware(app)

    # run the server

    uvicorn.run(
        app,
        host=HOST,
        port=PORT,
        log_config=logging_config,
        interface="wsgi"
    `)``
    
  Since it is only needed in deployment only, will have to add cli option i guess?

**Comment by mohanish2504** [comment]
Another alternative can be running as gunicorn app with worker config

**Comment by shahargl** [comment]
I thought to update the Dockerfile so it will be able to run as such

**Comment by shahargl** [comment]
ofc should be optional

**Comment by shahargl** [comment]
Like - if production => run with processes

**Comment by mohanish2504** [comment]
> I thought to update the Dockerfile so it will be able to run as such

So if I do something like `uvicorn app.main:app --workers 4` removing `keep --json api`
seems okay?

**Comment by shahargl** [comment]
yea, will need to verify it works and distinguish between dev/prod or something
